test: docker run --name ${APP_NAME} --rm ubuntu /bin/bash -c "while true; do echo -e 'HTTP/1.0 200 OK\r\n\r\nweb_server v0.1' | nc -l 80 ; done"
watcher: sleep 1 && docker inspect --format='{{.NetworkSettings.IPAddress}}' ${APP_NAME} && sleep 10 && echo Cleaning Up... && docker stop -t 3 ${APP_NAME} && echo Done...
